### ISSUE TITLE
Mag_Induced2D crashes

### ISSUE THREAD

**Issue by orerocks** [geoscixyz/gpgLabs#108]
Error:
```
/srv/conda/lib/python3.7/site-packages/gpgLabs/Mag/Simulator.py in plotMagSurvey2D(survey, a, b, npts, data, pred, fig, ax, vmin, vmax)
    216 
    217     # Use SimPEG.PF ploting function
--> 218     PF.Magnetics.plot_obs_2D(rxLoc, d=data, fig=fig,  ax=ax,
    219                              vmin=vmin, vmax=vmax,
    220                              marker=False, cmap='RdBu_r')

AttributeError: module 'SimPEG.PF.Magnetics' has no attribute 'plot_obs_2D'
```

has `PF.Magnetics.plot_obs_2D` moved to `Utils.PlotUtils.plot2Ddata`?

**Comment by fourndo** [comment]
you got it. But you will have to change the function call a bit, not all variables made it through.

**Comment by orerocks** [comment]
I tried to test it (and maybe even fix it) but I can't get the GPG Apps to run locally - only through the binder. Not a big deal I mainly wanted to use the MagneticDipoleApplet, which works fine.

**Comment by orerocks** [comment]
Ok, I think managed to fix #108 and #109 locally, but I don't have permission to push to gpgLabs. @lheagy can I please get write access?

**Comment by thast** [comment]
@orerocks : I added you to the `GeoSci` organization. That should give you write access. Let me know if that does not work.

**Comment by orerocks** [comment]
Thanks @thast. That did it!

**Comment by lheagy** [comment]
Excellent thanks for pushing on this @orerocks!! In the future, we are working to have the [geosci-labs](https://github.com/geoscixyz/geosci-labs) repo be the "warehouse" repo that in a sense is the source of truth, and then we update this repo and the [em-apps] based on those notebooks. 

We haven't yet gotten `gpgLabs` tracking `geosci-labs` yet, so some issues here might have already been fixed there. Before you spend too much time de-bugging code here, please take a look at [geosci-labs](https://github.com/geoscixyz/geosci-labs), and see if they are up-to-date and working over there. If not, we can definitely port your fixes over there too 

I will start an issue so that we can track the progress of transitioning this repo to follow geosci-labs.

**Comment by orerocks** [comment]
Ah. Indeed. Looks like it was all taken care of already.

I got to gpgLabs from the Geosci.xyz binder which linkS to gpgLabs. But now that I have figured out all the dependencies to run it from source I will track geosci-labs instead. Sorry for the hassle.

Thanks.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by lheagy** [comment]
No hassle at all. Thanks for catching this - it is important that we get things synced up to prevent confusion for others in the future. 

I will work on getting this repo updated so that wires don't get crossed.
